/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BtnAiSelect: typeof import('./src/common/button/btn-ai-select.vue')['default']
    BtnChatItem: typeof import('./src/common/button/btn-chat-item.vue')['default']
    BtnChatNew: typeof import('./src/common/button/btn-chat-new.vue')['default']
    BtnNavClosed: typeof import('./src/common/button/btn-nav-closed.vue')['default']
    BtnUserMenu: typeof import('./src/common/button/btn-user-menu.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    NotFound: typeof import('./src/common/views/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewChatBubble: typeof import('./src/common/views/view-chat-bubble.vue')['default']
  }
}
